services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    command: pnpm dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - URL_DEPLOY=${URL_DEPLOY:-http://localhost:3000}
    volumes:
      - ./:/app
    networks:
      - api_net
    restart: always

networks:
  api_net:
    driver: bridge

volumes:
  api_volume:
