services:
  api:
    build: .
    container_name: api
    command: sh -c "pnpm run db:generate && pnpm run db:migrate && pnpm start"
    ports:
      - ${PORT:-80}:${PORT:-80}
    environment:
      - PORT=${PORT:-80}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - URL_DEPLOY=${URL_DEPLOY:-http://localhost:${PORT:-80}}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-mydb}}
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
    networks:
      - api_net
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:${POSTGRES_PORT:-5432}/tcp
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api_net
    restart: unless-stopped

networks:
  api_net:
    driver: bridge

volumes:
  api_volume:
  db_volume:
