services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    command: pnpm dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - URL_DEPLOY=${URL_DEPLOY:-http://localhost:3000}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@db:5432/${POSTGRES_DB:-mydb}?schema=public}
    volumes:
      - ./:/app
    networks:
      - api_net
    restart: always

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api_net

networks:
  api_net:
    driver: bridge

volumes:
  api_volume:
  db_volume:
